[workspace.package]
version = "0.1.0-rc1"
edition = "2021"
description = "Community crate for XR in Bevy"
repository = "https://github.com/awtterpip/bevy_oxr"
license = "MIT/Apache-2.0"

[workspace]
resolver = "2"
members = ["crates/*", "crates/bevy_openxr/examples/android"]

[workspace.dependencies]
bevy = { version = "0.14.0", default-features = false, features = [
	"bevy_render",
	"bevy_core_pipeline",
	"bevy_winit",
	"bevy_pbr"
] }
