[package]
name = "bevy_xr_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
bevy_xr.path = "../bevy_xr"
openxr = "0.18.0"
bevy_openxr.path = "../bevy_openxr"
